// Copyright 2026 YANG
// SPDX-License-Identifier: GPL-2.0-or-later
// AUTO-GENERATED by tools/gen_menu_font.py from gfx/fonts/cozette.bdf -- do not edit.
//
// Uncompressed 8bpp coverage glyph table for the core1 LCD blitter. Cozette's
// native bitmap is 1bpp, so coverage is only 0 or 255; the blitter multiplies it
// by the draw alpha and blends the fg colour over the framebuffer.
//
// Monospace: the blitter advances a fixed MF_ADVANCE px per glyph regardless of
// `w`. `w` is only the stored ink width; a few glyphs are 7px and overhang
// the advance by 1px on purpose (blocks tile; others sit over the next blank col).
#pragma once

#include <stdint.h>

typedef struct {
    uint16_t off; // byte offset into mf_cov
    uint8_t  w;   // stored ink width in px (6 or 7); NOT the advance
} mf_glyph_t;

#define MF_LINE_HEIGHT 13
#define MF_ADVANCE     6
#define MF_ASCII_FIRST 0x20
#define MF_ASCII_COUNT 95
#define MF_UNI_COUNT   21

extern const uint8_t    mf_cov[9204];
extern const mf_glyph_t mf_ascii[MF_ASCII_COUNT];
extern const uint16_t   mf_uni_cp[MF_UNI_COUNT];
extern const mf_glyph_t mf_uni[MF_UNI_COUNT];
