// Auto-generated by make_tiles.py — do not edit.
#pragma once
#include <stdint.h>

#define WFC_TILE_PX     16u
#define WFC_TILE_BYTES  512u
#define WFC_TILESET_N   4u

#define WFC_CIRCUIT_TILES  16u
#define WFC_PIPES_TILES  16u
#define WFC_DUNGEON_TILES  25u
#define WFC_ISLAND_TILES  18u

typedef struct {
    const char    *name;
    uint8_t        n;
    const uint8_t *rgb565;
} wfc_tileset_blob_t;

extern const wfc_tileset_blob_t wfc_tilesets[WFC_TILESET_N];
